#title: Upper-Rhine and Tributaries Algebraic Geometry Seminar
title: URTAGS
email: pieter.belmans@uni.lu
description:
  The Upper-Rhine and Tributaries Algebraic Geometry Seminar is a regular seminar,
  jointly organised by several universities in France, Germany, Switzerland and Luxembourg.

plugins:
  - jekyll-redirect-from

# build settings
theme: minima

sass:
  quiet_deps: true

header_pages:
  - 2026-juin.markdown
  - past.markdown
  - about.markdown

exclude:
  - README.md
